marks = []
a = int(input("Enter the marks: "))
marks.append(a)
b = int(input("Enter the marks: "))
marks.append(b)
c = int(input("Enter the marks: "))
marks.append(c)
d = int(input("Enter the marks: "))
marks.append(d)
e = int(input("Enter the marks: "))
marks.append(e)
r = int(input("Enter the marks: "))
marks.append(r)
g = int(input("Enter the marks: "))
marks.append(g)
marks.sort()
print("The fruits are: ",marks)