fruits = []
a = input("Enter the fruit name1: ")
fruits.append(a)
b = input("Enter the fruit name2: ")
fruits.append(b)
c = input("Enter the fruit name3: ")
fruits.append(c)
d = input("Enter the fruit name4: ")
fruits.append(d)
e = input("Enter the fruit name5: ")
fruits.append(e)
r = input("Enter the fruit name6: ")
fruits.append(r)
g = input("Enter the fruit name7: ")
fruits.append(g)
print("The fruits are: ",fruits)
#print("The fruits are: ",a,b,c,d,e,r,g)