name = input("Enter name: ")
marks = int(input("Enter marks: "))
phone = int(input("Enter number: "))
s = (f"The name of the student is {name} and he got {marks} marks and his phone number is {phone}")
print(s)